# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=100)),
                ('block', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('trap', models.CharField(max_length=200)),
                ('AandS', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=20)),
                ('Aacc', models.IntegerField()),
            ],
        ),
    ]
