# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrow1', '0002_auto_20180929_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField()),
            ],
        ),
    ]
