# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-29 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrow1', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='Aacc',
            new_name='AddressAccuracy',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='AandS',
            new_name='AddressNumberAndStreet',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='block',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='longitude',
            new_name='Longitude',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='species',
            new_name='Species',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='street',
            new_name='Street',
        ),
        migrations.RenameField(
            model_name='musk',
            old_name='trap',
            new_name='Trap',
        ),
    ]
